CREATE TABLE [dbo].[Attachment]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[CreatedBy] INT NULL REFERENCES [User]([Id]) ON DELETE SET NULL,
	[CreatedAtUtc] DATETIME NOT NULL DEFAULT(GETUTCDATE()),
	[MedicalCardRecordId] INT NOT NULL REFERENCES [MedicalCardRecord]([Id]) ON DELETE CASCADE,
	[Name] NVARCHAR(512) NOT NULL,
	[Content] VARBINARY(MAX) NOT NULL
)
