CREATE TABLE [dbo].[MedicalCardRecord]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[MedicalCardId] INT NOT NULL REFERENCES [MedicalCard]([Id]) ON DELETE NO ACTION,
	[AssociatedRecord] INT NULL REFERENCES [MedicalCardRecord]([Id]) ON DELETE SET NULL,
	[DoctorId] INT NULL REFERENCES [Doctor]([Id]) ON DELETE SET NULL,
	[AddedAtUtc] DATETIME NOT NULL DEFAULT(GETUTCDATE()),
	[ModifiedAtUtc] DATETIME NOT NULL DEFAULT(GETUTCDATE()),
	[Content] NVARCHAR(MAX) NOT NULL
)
