CREATE TABLE [dbo].[UserGadgetSession]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[UserId] INT NOT NULL REFERENCES [User]([Id]) ON DELETE CASCADE,
	[GadgetId] INT NOT NULL REFERENCES [Gadget]([Id]) ON DELETE CASCADE,
	[StartDateUtc] DATETIME NOT NULL DEFAULT (GETUTCDATE()),
	[LastRequestDateUtc] DATETIME NOT NULL DEFAULT (GETUTCDATE())
)
