CREATE TABLE [dbo].[UserRole]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[UserId] INT NOT NULL REFERENCES [dbo].[User]([Id]) ON DELETE CASCADE,
	[RoleId] INT NOT NULL REFERENCES [dbo].[Role]([Id]) ON DELETE CASCADE,
)
